base:
  project: e-jagriti-project
  random_state: 42
  target_col: case_category_id

data_source:
  s3_source: data_given/new_consumer.csv

load_data:
  raw_dataset_csv: data/raw/new_consumer.csv

split_data:
  train_path: data/processed/train_new_consumer.csv
  test_path: data/processed/test_new_consumer.csv
  test_size: 0.2

estimators: 
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89
  Ridge:
    params:
      alpha_ridge: 1.0
  DecisionTree:
    params:
      max_depth: 5
      min_samples_split: 2


model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

